"""The round-trip gate (ADR-0002).

The canonical tree is the source of truth; Markdown is a projection of it. The
binding rule is that the projection is lossless for the defined profile:

    from_markdown(to_markdown(tree)) == tree

This test is the enforcement. A new block type is not finished until it is
generated by tests/strategies.py and this gate stays green for it.
"""

from __future__ import annotations

import pytest
from hypothesis import HealthCheck, given, settings

import template_engine as te
from template_engine._pandoc import api_version
from tests.strategies import dokumente

# Each example spawns pandoc twice, so latency is dominated by process start-up,
# not by the logic under test. Disable the per-example deadline for that reason
# and keep the example count modest; correctness, not fuzzing volume, is the aim
# at this stage.
_settings = settings(
    max_examples=60,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow],
)


@_settings
@given(dok=dokumente())
def test_baum_ueberlebt_die_rundreise(dok: te.Dokument) -> None:
    assert te.from_markdown(te.to_markdown(dok)) == dok


def test_pandoc_is_available() -> None:
    ver = api_version()
    assert isinstance(ver, list) and len(ver) >= 2


def test_realistisches_dokument_mit_metadaten() -> None:
    dok = te.Dokument(
        bloecke=[
            te.Ueberschrift(1, "Ausgangslage"),
            te.Absatz("Acme Corp plant die Konsolidierung ihrer Systeme."),
            te.Ueberschrift(2, "Vorgehen"),
            te.Absatz("Wir gehen in drei Schritten vor."),
            te.Ueberschrift(3, "Analyse"),
            te.Absatz("Zunaechst erheben wir den Bestand."),
        ],
        metadaten={"titel": "Migrationsbeurteilung", "stilprofil_version": 3},
    )
    assert te.from_markdown(te.to_markdown(dok)) == dok


def test_markdown_metazeichen_ueberleben() -> None:
    # An anchored regression example: characters that Markdown treats specially
    # must survive as literal text, so a future change that breaks escaping
    # fails here even if Hypothesis happens not to generate the case.
    dok = te.Dokument(
        bloecke=[
            te.Absatz("Kosten: $5 * 3, #tags, _kein_ [Link] und ein \\ Backslash."),
            te.Absatz("Zeichen wie > | ~ ^ und «Anfuehrung» mit — Gedankenstrich."),
        ]
    )
    assert te.from_markdown(te.to_markdown(dok)) == dok


def test_unsupported_inline_fails_loudly() -> None:
    # Emphasis is not in this catalogue. The surface must refuse to silently
    # drop it, which is the whole point of the loud-failure contract.
    with pytest.raises(ValueError):
        te.from_markdown("Ein *betonter* Absatz.")
